### ISSUE TITLE
Rename delimeter @ in route class

### ISSUE THREAD

**Issue by kopiyka** [simple-mvc-framework/framework#157]
The delimeter looks strange, whats about :: ?

Router::any('', 'Controllers\Page::index');

**Comment by daveismyname** [comment]
Hi, since I introduced routes it's used @ I think it's more pronounceable then :: when you think about it describing Controllers\Page@index sounds like: go to controllers then page at the index method.

The other reason to keep it @ is it's that way in all the docs and videos changing it would potentially cause a lot of confusion for no real gain.
