### ISSUE TITLE
New Bootstrap Version 3.3.5 and new release of SMVC

### ISSUE THREAD

**Issue by nekomajin** [simple-mvc-framework/framework#192]
Hello @daveismyname.
On 15 June 2015 a new version of Twitter's Bootstrap appeared: [Bootstrap 3.3.5 released - Bootstrap Blog](http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/). Would you please adjust this in the code? 

And when is a new release of SMVC planned? There have been many changes in the meantime (many changes at the code, new methods, a new API documentation - very great work! :thumbsup:).

Greetings

**Comment by jimgwhit** [comment]
@nekomajin what do you mean a new version of the framework? The framework was just completely updated even a new section of the router so it's PHP 7 compatible what more of an update could you possibly be talking about just curious?

**Comment by daveismyname** [comment]
Thanks I've upgraded to 3.3.5, I have no plans for a new release at this time.

I'm in the process of making the documentation available offline.
Also going through the framework and creating snippets for Sublime Text.

**Comment by jimgwhit** [comment]
I agree with the above, basically the tweaks to make this version compatible with php 7 is like a new version.  I guess some aren't happy unless a new number is assigned to something.  I guess you could call it Simplemvc framework version 7 or something. Same framework with a new name.  
But that aside, it's great how you have brought it up the the new psr specs.  And thanks to volter9 for helping me figure out the router compatibility with php 7.

**Comment by volter9** [comment]
@jimgwhit well, the most of the testing and work was done by you, I just proposed several options to correct :wink:

**Comment by nekomajin** [comment]
@jimgwhit: it was just a question. [heiseonline / shariff](https://github.com/heiseonline/shariff/releases) publish in a short time and even with smaller bug fixes, as you can see. I just wanted to know how @daveismyname's release strategy looks like.

**Comment by jimgwhit** [comment]
Here is my take.  On the home page of SMVC there is a picture with a yellow stickee note with a reminder:  
~~~
KEEP IT SIMPLE
~~~
Now with that said, I have nothing against an advanced version, but another branch or something, or something with a different name.  I drew to this framework because of the keep it simple philosophy.  I can't get over people wanting more and more.  
What they don't realize is you can modify / tweak / change a framework to custom fit your needs, all without messing with the original on github.  Some people think it's like a CMS, it's not.  
Please, at least let's keep it simple, but maybe Dave can come up with an advanced version elsewhere on github with more features.  
I just believe in getting the basic framework, and customizing it to that sites needs, without sending in 10 rediculious pull request of every little thing the framework didn't do.  
When I buy a welding rod, I don't expect the project to be welded already, no I consume the rod in making my own custom metal project.  
Now if it's something very useful that most sites will probably use, and if it keeps it simple well then consider a pull request. Example, there are millions of combinations of ways to custom write queries.  
Can you imagine the database helper having every possible combination of ways to perform custom queries?  The database helper alone would be 20 gigabytes in size. But some people want this -- GEES.  That;s why frameworks have raw, so a person can write a custom query.  So the PR for the custom query was fine.
I guess to me less is better in a framework.  You know you could have addons people could include in composer if wanted, without forcing me to use something that Joe Blow wants, or him to use something that I want.

**Comment by jimgwhit** [comment]
Also @nekomajin said 
~~~
heiseonline / shariff publish in a short time and even with smaller bug fixes
~~~
This may be true of a super, huge framework.  But most fixes in SMVC is the php version you are using.  Think about it, it's PHP and PDO based, not some other wrapper.  So the framework is small, most "bugs" if any will be corrected by the user of the framework when he or she does a site.  Dave's classes aren't 1.5 million lines long like z__d and another we all know L_____. Actually it's almost impossible to have a bug in this framework, if your page loads and works as expected = no bugs.  It's just to small to worry about.  That's why I like it.  
Take the SMVC and logger error Dave fixed. I guess that's a bug, but most users will catch this stuff and fix it and put in a issue. Isn't that why Github, self correction?

**Comment by volter9** [comment]
@jimgwhit whoa! That was a pretty sharp response :smile: 

Don't worry, I didn't planned to pull request my changes to this repository, at least share with you in a new issue, guys. This repository shouldn't be over bloated, however, it's already with all these helpers.

Although I completely agree with what you pointed out about heavy frameworks. I wonder, why does frameworks like Symfony has tons of classes which are 400-2k lines long.

> z__d and another we all know L_____.

These look like new curse words :laughing: 

> What the z__d is going on here?
> Are you a L_____?

**Comment by daveismyname** [comment]
@jimgwhit don't worry no drastic changes are going to be made, I love the passion but lets all try to get along we are all trying to accomplish the same thing.

They will be minor updates from time to time to make improvements where appropriate but I'm not planning a major release anytime soon, each release requires a lot of work new documentation, screencasts, bug checking...etc 

@volter9 I know what you mean with regard to the helpers one thing I plan to do is create a add-ons section of the website that links up to other people's helpers located on Github that they the framework it's not getting more bloated and the end user can decide if they want to include extra helpers.

This has the added benefit that the authors will be able to self document the helper which in turn will show up on the website.

I use a fair amount of helpers not included with the framework as they are specific to projects I'm working on, not everything needs to be included. That's where composer comes in too things like Facebook and Dropbox SDK's I use composer for rather then making helpers for them.

**Comment by nekomajin** [comment]
@jimgwhit: First I want to thank you for your detailed and honest opinion. Also I have fallen in love with SMVC because it represents these "Keep it simple" philosophy.

The example with [Heiseonline / Shariff](https://github.com/heiseonline/shariff/releases) was only a question in conjunction with an example, as I had written in my message https://github.com/simple-mvc-framework/framework/issues/192#issuecomment-141826766.

I do not ask and will never require that for every little thing a new Major.Minor.Patch-beta+exp.sha.5114f85-pre-release+alpha will release.

On the contrary: at the home page of GitHub there are four important points in relation to the community in planning and creating code and the resulting software (scroll down to "Why you'll love GitHub"). That's one important reason why I decided to GitHub as the platform and SMVC as my favourite framework.

@daveismyname manages very well to provide us a working base, without it being so bloated like the Zend Framework, Symfony, Laravel and other (why you don't write in full?). Although I must say that these frameworks are trying to cover a lot of contingencies and are more suitable for very large projects. And before that is again misinterpreted: Even SMVC is certainly suitable, with adjustments from the user, for very large projects. At least, it provides a solid base. Like the foundation of a house: Without a foundation a house can't stand alone. But without adaptations and extensions it will never an individual house.

In Issue #191 I first asked the community what you think of standardized comments. And have named examples. There was not even thinking about PR's. @daveismyname has taken on this matter and reacted super. He also created a current API documentation. Fantastic thing!

I don't want the SMVC become to large and covers all eventualities. On the contrary: It should allow me the freedom to be able to contribute my own wishes. And that makes it even. Thanks @daveismyname for your hard work. Keep it up! Many thanks.

**Comment by jimgwhit** [comment]
Ah, these last comments are encouraging, feel better already.  
@daveismyname said
~~~
I plan to do is create a add-ons section of the website that links up to other people's helpers located on Github
~~~
Where on github, are you talking about a place on github you would have or I would have to have for my addons?  All I currently have on github is a fork to SMVC.
Anyway thanks everyone, we all agree to keep it simple and clean-cut.  
@volter9 yeah, I don't like huge frameworks.  Using regular php/pdo, a little security, it only requires a few lines of code to query a record.  Some seem to think it requires thousands of lines of code.  
That's why I like SMVC.

**Comment by daveismyname** [comment]
The author would host the addon on their GitHub then they have full control over it.

Authors would submit them on the website they would be reviewed and added to the site, all the information would be pulled from the authors repo

Sent from my iPhone

On 21 Sep 2015, at 17:20, jimgwhit <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, these last comments are encouraging, feel better already.

@daveismyname<https://github.com/daveismyname> said

I plan to do is create a add-ons section of the website that links up to other people's helpers located on Github


Where on github, are you talking about a place on github you would have or I would have to have for my addons? All I currently have on github is a fork to SMVC.
Anyway thanks everyone, we all agree to keep it simple and clean-cut.

@volter9<https://github.com/volter9> yeah, I don't like huge frameworks. Using regular php/pdo, a little security, it only requires a few lines of code to query a record. Some seem to think it requires thousands of lines of code.

That's why I like SMVC.

-

**Comment by jimgwhit** [comment]
On my forked SMVC, am I allowed other places to put code?  I only have the free account.

**Comment by daveismyname** [comment]
Yes you can have many repos on a free account I'm using a free account for SMVC.

Sent from my iPhone

On 21 Sep 2015, at 18:32, jimgwhit <notifications@github.com<mailto:notifications@github.com>> wrote:


On my forked SMVC, am I allowed other places to put code? I only have the free account.

-

**Comment by jimgwhit** [comment]
@daveismyname , later when you start the (other people's helpers located on Github), if a user wants to pull it in using composer, then I don't know how to give instructions for that.  Can you give an example using a little fake class or something how to add a class / file from github using composer?  I take it that it would have to be included in the auto loading, is that correct?  
I use composer for installs, but never used it like this.

**Comment by daveismyname** [comment]
with them being external your free to choose how to include them I think most of the time they will be modules or helper classes in which case composer won't be needed. The file/s are downloaded and added to your framework.

likewise if you want to use composer using packagist.org makes it easy to install from composer but it's not required. Either way no autoloading changes would be needed.

I'll let you know when this is in place, it's going to be awhile I don't have much free time at the moment.
