### ISSUE TITLE
Proposed router change

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#232]
@LuckyCyborg in your proposed router if I had this route
```
Router::any('pet', 'Controllers\Pet@index');
```
This URL
```
site/pet?p=2&search=b&color=black
```
Are you saying that the new way of getting  
that data in the controller is:
```
public function index($str = '')
$t1 = Request::get('search');
$mycolor = Request::get('color');
//other code here.
```
And the $str='' has to be there for it to work?  You never gave a controller
example.  I just find it odd that a str='' would need to be there.  It would make more since
to have a way for user to choose friendly url or querystring in a config file.  
That way if a regular querystring is going to be used the controller method  
would still start like:
```
public function index()
```
And if friendly url like
```
public function index($p='', $search='', $color='')
$currpage = $p;  //empty string if empty.
$t1 = $search;
$mycolor = $color;
```
But I have never seen where you have to have anything in the parenthesis  
if working with the querystring.  And POST data hasn't even been asked yet.

**Comment by LuckyCyborg** [comment]
@jimgwhit  Like I said, please just ignore this feature; is nothing magic, is nothing useful for majority of us. If you are really curious about to what use us this thing, I will say in few words: for fast **Api Access Authorization**

It is something like this: our **\MVC\Core\Controller** , equivalent of SMVC's **\Core\Controller**, is somewhat more complicated, and the **Router** do not call the Controller's Methods directly, instead it call a method present in the base Controller, defined as **execute($method, array $params)**. That entry method do a pre-flight setup, execute the right method if is case and do a post-flight processing.

And in the **API**, there is a machine communication protocol, because the named Portal is formed from 5 websites with very different tasks, which is secured via HTTPS and some authorizations keys.

So,  the Controllers from the API, in their Method's **pre-flight**, check the QUERY_STRING, combined with an Authorization Header and a Secret AuthKey. If something go wrong, they kick-out the Request, literally before to execute the current asked Method. 

To note that the **real** QUERY_STRING on SVMC case is something like:
```
/admin/books/list&page=5&search=jim
```
There is a first GET parameter, almost invisible for **$_REQUEST** and **$_GET**, but also for most spoofing applications, because it do not have a key, and its value is just the URI. 

That thing we speculated us and followed with an Auth Header and another shiny things, to make a simple but efficient machine API authorization; and we have no intention to decode the querystring passed by the Routing, and to use it for real in the (controller's) methods. I just mentioned that there is present this ability.

That's all. Happy now?

**Comment by jimgwhit** [comment]
Got it working, shame no one else helped test though.

**Comment by jimgwhit** [comment]
Thanks for bearing with me, like you I have production sites and get nervous with big chances.

**Comment by LuckyCyborg** [comment]
@jimgwhit Any WebMaster will react suspicious like a Grizzly Bear on the news that Core Component of his production Framework are proposed to be replaced. 

But, we like to believe that our code is careful tested and optimized first...

**Comment by jimgwhit** [comment]
@LuckyCyborg please see my latest comment on issue #222

**Comment by LuckyCyborg** [comment]
@jimgwhit  I read your comments, and I will look to issues. Sadly, we are on weekend and my colleagues will be available next week. Yet, I will continue tomorrow on Routing, and you'll see patches.

All the best!

**Comment by jimgwhit** [comment]
@LuckyCyborg  and @daveismyname 
I would like to better understand how to pass friendly url
so I could test router under different circumstances.
In the paginator page links, and if using querystring you would 
```
$data['pageLinks'] = $pages->pageLinks('?', '&search=' . $petsearch . '&mycolor=' . $color);
```
which makes url look like:
```
site/pet?p=3&search=b&mycolor=yellow
```
I am guessing the ? is still needed for the paginator, But I don't know.  
How would I change the page links so the url would look like this
```
site/pet?p=3/b/yellow
```
or is there a way to
```
site/pet/3/b/yellow
```
And I don't know how to deal with a blank parameter like
```
site/pet/3//yellow
```
Notice no search string so you would want all listed.  And in friendly url

**Comment by daveismyname** [comment]
for paginator I use query strings.

**Comment by jimgwhit** [comment]
@daveismyname  ok then hwo would page links part of the paginator be written to get this:
```
site/pet?p=3/b/yellow
```
see above examples

**Comment by jimgwhit** [comment]
@daveismyname actually, I plan on using regular querystrings anyway, I don't use the pretty url's.  I just want to do exhaustive both ways, because I know some folks do use pretty url's.  Funny thing is the querystring like:
```
site/pet?p=3&search=b&mycolor=yellow
```
is pretty to me.

**Comment by daveismyname** [comment]
as it stands I don't think it can work without query strings.

**Comment by jimgwhit** [comment]
@daveismyname a while back I wrote another pager that works with pretty url's, The only problem I have is I can't figure out how to make just one that works with querystring or pretty url's.  
After this router thing is resolved, can I send you an attached zip file of what I have, and maybe we can make it work, Just look it over.  It's a similar paginator, you just pass the parameters a little different.  I am still trying to make it so querystring or pretty will work.  
Bear in mind I am new to pretty url's, I don't use them, but started this out of curiosity.

**Comment by daveismyname** [comment]
Yeah can we wait as you've suggested. As we have quite a few different things going on.
Warmest Regards.
DAVID CARR
Web Developer
Email: dave@daveismyname.com (mailto:dave@daveismyname.com)
website: daveismyname.com (http://daveismyname.com)
website: phpcodesnippets.com (http://phpcodesnippets.com)
website: simplemvcframework.com (http://simplemvcframework.com)
Mobile: 07429 561 809
On Sat, Dec 12, 2015 at 07:37 PM, jimgwhit  wrote: 

	@daveismyname (https://github.com/daveismyname) a while back I wrote another pager that works with pretty url's, The only problem I have is I can't figure out how to make just one that works with querystring or pretty url's.

 After this router thing is resolved, can I send you an attached zip file of what I have, and maybe we can make it work, Just look it over. It's a similar paginator, you just pass the parameters a little different. I am still trying to make it so querystring or pretty will work.

 Bear in mind I am new to pretty url's, I don't use them, but started this out of curiosity.
