### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by EdwinHoksberg** [simple-mvc-framework/framework#46]
I would love to keep contributing to this project, but I have no idea what to do next.
Does anyone have an idea for a useful feature or something else?

**Comment by bakermanus** [comment]
I'd like see rest server helper. That would be nice.

**Comment by jimgwhit** [comment]
Volter9 you said:  
The only thing that comes me to mind is to simplify existing features, or fix something. The only thing is bugging me in SMVCF is Database class. The Database class is bad structured, on each model creation there's new instance created. Imagine yourself having 10 models, each model creates another connection to database, so that's lead to over duplicating of the database. It should be fixed!  
I don't believe this to be true, The database is only loaded when a call to it is made.  It's not like you have 10 models making calls all at once.  Other frameworks also have multiple models and make calls to the database wrapper when needed.  Also all these models aren't all loaded until you call for something in the controller.

**Comment by jimgwhit** [comment]
What do you think about creating widgets as a new feature?  
NO NO NO NO NO NO NO.  If you really want that junk go to yii framework.

**Comment by Volter9** [comment]
@jimgwhit I changed my mind long ago. Partial views are better.

**Comment by ennerperez** [comment]
Considerate replace get function with this one in Language.php, result usefull for me, to create .resx files style.

     /**
     * Get element from language array by key
     * @param  string $value
     * @param  int $index
     * @return string
     */
    public function get($value, $index = NULL)
    {
        if (!empty($this->array[$value])) {
            if (!isset($index)){
                return $this->array[$value];
            }
            else {
                $return =$this->array[$value];
                return $return[$index];
            }
        } else {
            return $value;
        }
    }
