### ISSUE TITLE
router 3-13-2016

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#631]
@daveismyname for some reason after the 3-13-2016 router update I only get a blank page, any idea why?  The only change I noticed was
```
        empty($_GET['lang']) ? $lang = LANGUAGE_CODE : $lang = $_GET['lang'];
        Session::set("lang",$lang);
```
Would an isset be better?  
```
isset($_GET['lang']) ) ? $lang = $_GET['lang'] : LANGUAGE_CODE;
```
And quickly can you rename branch 3.0 to 3.0 on it's branch page, it shows as 2.2.  I can fork, fetch everything into master, but can't update origin on git.

**Comment by daveismyname** [comment]
I forgot to add the session helper to the use blocks at the top of the file, add this:

````
use Helpers\Session;
````

**Comment by jimgwhit** [comment]
@daveismyname see additions to comment above.

**Comment by daveismyname** [comment]
> And quickly can you rename branch 3.0 to 3.0 on it's branch page, it shows as 2.2. I can fork, fetch everything into master, but can't update origin on git.

I'm not following you the 3.0 branch is already called 3.0 the 2.2 branch is the current master branch

**Comment by LuckyCyborg** [comment]
@daveismyname You are kind to explain the sense of this command?

```php
   $requestUri = str_replace($_GET['lang'],'',$_SERVER['REQUEST_URI']);
```

Not only that do not help to something (the Router make a clear distinction between URI and GET parameters) but can produce strange problems, ie

```
/admin/entities/enabled
```

will become:

```
/admin/tities/abled
```

going to spectacular and mysterious Routing failures...

**Comment by jimgwhit** [comment]
@daveismyname if you go to https://github.com/simple-mvc-framework/framework then select 3.0 from the dropdown, the title is still showing Version 2.2 of the Framework http://simplemvcframework.com/ instead of Version 3.0 of the Framework http://simplemvcframework.com/

**Comment by daveismyname** [comment]
that title is the title of the repository, it's not tied to a branch. That will be updated when 3.0 is released I've got all the docs to write and finish my tests before that happens.

**Comment by jimgwhit** [comment]
Should be something like
```
$currentlanguage = $_GET['lang'],  // perhaps an isset logis, resort to default
$requestUri = $_SERVER['REQUEST_URI'] . $currentlanguage;
```
And of course however the ? question mark is handled.  
That string replace could cause goof-ups.

**Comment by LuckyCyborg** [comment]
@jimgwhit In fact, even that no make sense.

There should not be those  things. You known how the guys set usually the Site Language i.e. with CodeIgniter?

They just make a Language controller who have a method which accept a parameter, and setup the LANG into session. Voila! There is no need to mess with the Routing if you do not have Multi-Language Content. Where the crap hit the fan. Multi-Language enabled Controllers and Models.

Because you need Multi-Language Content. For example, having Blog Posts into English, Chinese, Spanish and Italian, switched by language parameters.

BUT, I believe that Multi-Language Content is far away from the doctrine of "simple mvc framework", then maybe is better to cut off those things at all.

**Comment by jimgwhit** [comment]
@LuckyCyborg couldn't you please be just a little nicer, be helpful, please not rude.  I can't speak for Dave, but you know I value your opinion and help.

**Comment by jimgwhit** [comment]
@LuckyCyborg I use frameworks as a database management tool.  I started out in dbase 3 plus late 80's.  I have used jsp with beans and servlets, visual foxpro, etc.  I am no expert on writing framesworks.  But I do try to test, help catch errors, etc.  I have been in php for several years.  But as far as a router, well you and Dave are the experts there.  Doing crud, writing complex queries, etc, I am pretty good at that.  That is what I like about this framework,  I wrote a checkbook program for a lady, who wanted running totals and
```
$sql = "SELECT OD.checkid, OD.transdate, OD.transdescribe, OD.widthdraw, OD.deposit, OD.isclr,";
        $sql = $sql . " (SELECT (Sum(IFNULL(deposit, 0)) - Sum(IFNULL(widthdraw, 0))) FROM checks";
        $sql = $sql . " WHERE checkid<=OD.checkid) AS RunningSum";
        $sql = $sql . " FROM checks AS OD" . $pagingQuery;
        $sth = $this->db->pdoPrepare($sql);
        //$sth = $conn->prepare($sql);
        $sth->execute();
        $results = $sth->fetchAll(\PDO::FETCH_ASSOC);
        return $results;

```
just had to add this to database helper
```
public function pdoPrepare($sql)
    {
       return $this->prepare($sql); 
    }

```
I know enough database stuff, but like I said routers, that's not my cup of tea.

**Comment by LuckyCyborg** [comment]
@jimgwhit Jim, I have no intention to be rude.

I just wondering about what Dave do right now into Routing...

**Comment by jimgwhit** [comment]
@LuckyCyborg You are absolutely correct about that str_replace function, I played with it using some variables.  So I am sure he will re-work it.  He has been good at quickly fixing stuff.  Maybe you could help with getting the language thing working without affecting the router P-L-E-A-S-E.

**Comment by daveismyname** [comment]
I've removed the language setup, I will relook at this at some point in the future when I have some time.

**Comment by LuckyCyborg** [comment]
@daveismyname A very wise decision, in my opinion.

In fact, the Multi-Lingual Content is not exactly the best thing to develop in "a very simple MVC framework". Trust me, because I written Multi-Lingual Content enabled frameworks, not only one time.

Wonder why I do not enabled that into beta? For a reason.

For everything else, the Language can be switched very simple using a dedicated Controller and some parameter. With a slightly improved Language class.

But what that guy want, French (left-to-right) and Arabian (right-to-left), switched on fly, well... he maybe do not use the right framrwork for that.

**Comment by daveismyname** [comment]
yes that old saying 'the right tool for the right job' is very fitting here.
